apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: argo-cd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: sample-project
  source:
    path: charts/helm-example
    repoURL: https://github.com/abhishakeonteddu/gitopps_repo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
